### ISSUE TITLE
Additional endpoint for creating releases after continuous integration passes

### ISSUE THREAD

**Issue by skye2k2** [fs-webdev/github-automator#17]
Use case: When a team desires to have their continuous integration build pass on master _prior_ to creating a new release.

Tree has an [auto-tag script](https://github.com/fs-webdev/tree-common-build-scripts/blob/master/bin/tag_build.sh) that runs during the `after_success` stage of their Travis CI builds. Ideally, they would like to POST the bare essentials needed to a new endpoint to create a new release at the time of their choosing.

Suggested URL: http://fs-github-automator.herokuapp.com/version-create
Suggested payload:
```
{
    "release_number": "X.Y.Z",
    "release_description": "The description to be attached to the release",
    "repository": "fs-webdev/fs-component-name",
    }
}
```

**Comment by joeycozza** [comment]
1. Has the commit to master already occurred at the point in time that travis is running all this? 
2. If so, at that point in time (during after-success), do you know the git commit-hash you are working with?
3. Is it guaranteed that you need to make a new release (the version was actually bumped during the commit), or do you just know the current version number in package/bower json?

**Comment by skye2k2** [comment]
1. Commit to master has occurred.
2. Yes, we have the `$TRAVIS_COMMIT` SHA available.
3. We just know the current version number, but we are checking via `git tag -l $BOWER_VERSION` to see if there are any pre-existing releases/tags for that number.

**Comment by joeycozza** [comment]
to be honest, at that point, it sounds like you have all the data, and knowledge (do i need to make a release, or is there already a release for this) to just hit the github API yourself, right?

We could make an endpoint for you to hit, but it would pretty much just take your data, and make 1 call to github's API. Are there any other benefits if we make this an endpoint here on github-automator?

**Comment by skye2k2** [comment]
So, the problem in Travis CI currently is that they have a default read-only SSH key created whenever a new repository gets added that trumps the `.netrc` file that we are supposed to be using for repo access. This makes it so that our `git push origin $VERSION` command fails out with: 

> ERROR: The key you are authenticating with has been marked as read only.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights

And our component repositories do not have any package.json dependencies, so using `fetch` adds that bloat. Using the org-supported release mechanism seemed like the right option.

**Comment by joeycozza** [comment]
That makes sense. Didn't know you had a readonly token.

Those 2 reasons make sense.

**Comment by skye2k2** [comment]
And if the manual and hook routes are both able to detect a pre-release `(\d+\.\d+\.\d+\D+)` (basically if word is appended to true semver convention) and add the flag when creating the release, that would be _epic_.

**Comment by joeycozza** [comment]
ooooh. I really like that.

**Comment by joeycozza** [comment]
https://github.com/fs-webdev/github-automator/pull/21
