### ISSUE TITLE
ENHANCEMENT: On server-side errors processing the release request, add message to Warning header

### ISSUE THREAD

**Issue by skye2k2** [fs-webdev/github-automator#27]
Currently an example bad request will result in a log entry on Heroku:

```
app[web.1]: Invalid Payload: Neither of the package.json or bower.json files were edited this commit.
```

but sends a response status of: `400` accompanied by unhelpful headers.

1. Distill all error messages down to no more than 7-word phrases (e.g. "Invalid Payload: Version not modified).
1. When logging on Heroku, note the repo that requested the version release.
1. Add a `Warning` header that contains the error message. Follows pattern utilized by TreeFoundation.

**Comment by joeycozza** [comment]
1. So do you want the response code to not be a 400?
2. How important is the 7-word length limit to you?

**Comment by skye2k2** [comment]
I think that a non-200 status is still appropriate. Something along the lines of: https://http.cat/406, https://http.cat/412, https://http.cat/417, or https://http.cat/422 / http://clif.herokuapp.com/422/animated would be fine. 

The final goal is not necessarily a 7-word response, but concise and easy to understand error messages that would immediately help consumers craft a correct request.

**Comment by joeycozza** [comment]
I still don't fully understand why this is helpful/important to have for this github-automator tool, but I have a PR that puts the error message in the Warning header. https://github.com/fs-webdev/github-automator/pull/29

At this time, I don't want to worry about making this a perfect beautiful example of a pristine json API or whatever. If you want better status codes for each of the different places we catch errors, you can figure out how to do it and take the time.
