### ISSUE TITLE
ENHANCEMENT: Remove /release endpoint server-side check to see if the version was changed 

### ISSUE THREAD

**Issue by skye2k2** [fs-webdev/github-automator#28]
Add a `skipEditedCheck: true` option that can be sent to the /release endpoint. Instead of making sure the package/bower.json was modified in the commit and pulling the file out of the files changed list, fetch the package/bower.json at that point in time, and just check to see if the requested release version matches what is in the file(s).

**Comment by joeycozza** [comment]
Using postman, I was able to get the raw file data from a specified commit. This code is the generated snippet from postman so I can use it later. But the important part is setting the ref=commitHash and putting the Accept header as application/vnd.github.3.raw

```javascript
var request = require("request");

var options = { method: 'GET',
  url: 'https://api.github.com/repos/joeycozza/configFiles/contents/zshrc',
  qs: { ref: '942c01e30bd6153c7a75c5888a9a661f4da0452f' },
  headers: 
   { 'Postman-Token': 'bb436d58-5b76-4e78-9aa0-845b18811254',
     'Cache-Control': 'no-cache',
     Accept: 'application/vnd.github.3.raw' },
  body: '{\n\t"repoName": "fs-tree-couple",\n\t"owner": "fs-webdev",\n\t"version": "0.1.1",\n\t"commit": "6b4cce2a8aa0505330ba73ed2b6f07ac726d8a41",\n\t"description": "using POST endpoint joey local testing"\n}\n' };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```
